# Generated by Django 5.0.2 on 2024-02-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_band_biography_alter_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
